"""Typed intent — what a person asked for, before it is a number.

THE LOAD-BEARING CONSTRAINT: a 20B model must be able to fill this in on the
first try. That is the entire reason the module exists, and it forces two rules
that are not negotiable:

  * NO FLOATS. Every field is a closed vocabulary. A model that has to invent
    `temperature: 1470` is doing the job `compiler.py` does from measurement,
    and doing it by guessing — which is exactly what GradeSpec's 44 numbers
    already ask of it (see looks.py's docstring for how badly that goes).
  * FEW ITEMS. A real grade is three to eight moves. Intent stays ~5 items no
    matter how capable the compiler becomes; new expressiveness lands as a new
    verb and a new compiler pass, never as more numbers for the model.

An Intent is not a grade. It carries no magnitude a renderer could use — only a
direction and a coarse amount. `compiler.compile_intent(intent, stats)` turns it
into a GradeSpec by consulting the clip's MEASURED statistics, which is where
"moderate warm" finally becomes a number.

The second reason for this shape: it is human-readable by construction.
`describe()` renders an Intent as short English, so the UI can show four
sentences instead of 44 sliders (roadmap C3/C4).

COVERAGE OF GradeSpec. Every field GradeSpec can express is reachable from some
verb here, except three that deliberately have none:

  * `pivot` — not a thing anybody asks for. The compiler derives it from the
    measured median luma whenever it applies contrast.
  * `contrast_balance` — not a thing anybody asks for BY NAME, but very much a
    thing they ask for: it is which end of the curve `contrast` lands on, and
    the `shadows` and `shoulder` verbs write it between them.
  * `saturation_balance` — the same, one axis over: which end of the tone scale
    `saturation` lands on. `shadow_saturation` and `highlight_saturation` write
    it, and a plain `saturation` writes the 0 that says "evenly".
  * `rationale` — generated by describe(), so the model no longer writes it.

*That list used to name `highlight_rolloff` too — "a consequence, not a
request: the compiler adds a shoulder when it is about to create highlights,
exactly as match.py does" — and it stopped fitting the day a sentence could ask
for the shape of the top end (roadmap B3).* The old wording was true about one
of the two cases and silent about the other. A shoulder IS derivable when it is
a consequence of a brightening move, and `_protect_highlights` still derives it
there, unchanged. It is NOT derivable when the shoulder is the look — "keep the
highlights soft" names no brightness change at all, so there is nothing for the
compiler to infer it from, and before `shoulder` existed that sentence moved
literally nothing. The two compose through `max()`, so the derived case is
untouched: a shoulder the grade needs and a shoulder the user asked for are one
knob and the larger wins.

`slope` has no verb of its own either: as a *brightness* tool `exposure` beats
it (it sits before the CDL, so `offset` stays an absolute lift), and as a
*colour* tool it is what match.py solves for. The compiler still writes slope
when a verb needs per-channel gain.
"""

from __future__ import annotations

from typing import Literal, get_args

from pydantic import BaseModel, Field, model_validator

from .segment import CLASSES

# The verb vocabulary. Twenty words, each a thing a person says out loud about a
# picture. Nineteen of them MOVE something and take a direction and an amount;
# the twentieth, `protect`, names pixels for the other nineteen to skip. `dir` means up/down on that axis and is documented per verb below.
OpName = Literal[
    # tone
    "exposure",        # up = brighter overall
    "contrast",        # up = punchier
    "midtones",        # up = brighter mids only (compiler inverts it onto `power`)
    "shadows",         # up = lifted/faded blacks
    "highlights",      # up = brighter whites
    "shoulder",        # up = the whites roll off softly; down = they arrive hard
    # colour
    "warmth",          # up = warmer/oranger
    "tint",            # up = magenta, down = green
    "saturation",      # up = more colourful
    "shadow_saturation",     # up = more colour in the dark half only
    "highlight_saturation",  # ... and in the bright half only
    "shadow_tint",     # push `target`'s colour into the dark half
    "highlight_tint",  # ... and into the bright half
    # texture (EffectSpec — spatial, never baked into the LUT)
    "grain",
    "glow",
    "vignette",        # up = darker corners
    "softness",        # up = softer, down = sharper
    "denoise",
    "fringe",
    # selection (roadmap B6) -- "...but don't touch the sky". It writes no
    # GradeSpec field at all: compiler.compile_stack subtracts its region from
    # every other op's, so it is a verb by grammar and a mask by mechanism.
    # `dir` and `amount` are meaningless on it (a region is in or out) and
    # describe() deliberately reports neither.
    "protect",
]
OPS = get_args(OpName)

# Verbs that answer "which pixels" instead of "what changes". Named here rather
# than spelled `== "protect"` in three files: compiler.py has to keep them OUT
# of the per-verb table (a verb with no compiler entry is normally a bug, and
# this is the one exception), and describe() has to render them without a
# direction or an adverb.
MASK_OPS = ("protect",)

Direction = Literal["up", "down"]
DIRECTIONS = get_args(Direction)

# Coarse magnitude. Three words, not a number: the difference between "a bit
# warmer" and "much warmer" is the only magnitude information a sentence
# actually carries, and it is the only magnitude a model can supply reliably.
Amount = Literal["subtle", "moderate", "strong"]
AMOUNTS = get_args(Amount)

# What the op acts on. "" is the whole frame and is the overwhelming default.
# One field, three kinds of answer to "which pixels", and the reason they share
# a field is that a sentence does not distinguish them — "darken the blues",
# "darken the top" and "darken the sky" are the same shape of request:
#
#   * a COLOUR name routes saturation/exposure onto the hue qualifiers, and
#     names the colour to add for the two tint verbs. `skin` is one of these: it
#     is a hue family, and it stays one even now that a segmentation model is
#     available. ADE20K has no skin class, and a hue qualifier tracks a face
#     through movement and a cut for free where a per-frame matte does not.
#   * a GEOMETRIC REGION selects by where a pixel SITS.
#   * a SEMANTIC REGION (roadmap B2) selects by what a pixel IS PART OF —
#     the five things segment.py's model can name well enough to grade.
#
# region.py holds the Region each of the last two means, so the word and the
# mask cannot drift apart, and compile_stack resolves both through one lookup.
Target = Literal[
    "", "red", "orange", "yellow", "green", "cyan", "teal", "blue",
    "magenta", "purple", "skin",
    "top", "bottom", "left", "right", "center", "edges",
    "sky", "foliage", "person", "water", "buildings",
]
TARGETS = get_args(Target)

# Targets that answer "which pixels" spatially, in one tuple so compiler.py and
# describe() agree without either holding a second list. GEOMETRIC and SEMANTIC
# differ only in where the mask comes from; every consumer here treats them the
# same, which is the point of B2 being a mask source rather than an
# architecture. SEMANTIC is derived from segment.CLASSES rather than retyped so
# the two cannot disagree (the Literal above still has to spell them: a Literal
# cannot be built from a runtime tuple, and a test asserts they match).
GEOMETRIC = ("top", "bottom", "left", "right", "center", "edges")
SEMANTIC = tuple(CLASSES)
REGIONS = GEOMETRIC + SEMANTIC

# The six EffectSpec verbs. They are ALREADY spatial -- they live in render.py's
# filter chain, not in the LUT -- so masking one means masking a filter rather
# than masking a grade, which is a different piece of plumbing and not this
# item. A region on one of these is dropped on the way in (see Op), because the
# alternative is describe() printing "added grain in the top" for something that
# happened everywhere.
EFFECT_OPS = ("grain", "glow", "vignette", "softness", "denoise", "fringe")

# How much of the whole look survives -> GradeSpec.look_mix. A separate field
# rather than a verb because it is a property of the request, not an operation,
# and because "half strength" modifies everything else that was asked for.
Strength = Literal["full", "strong", "moderate", "subtle"]
STRENGTHS = get_args(Strength)

# Defined here, not in the compiler: describe() quotes these percentages back to
# the user, and a sentence that disagrees with the grade is a bug.
STRENGTH_MIX: dict[str, float] = {
    "full": 1.0, "strong": 0.85, "moderate": 0.65, "subtle": 0.4,
}


class Op(BaseModel):
    """One requested move. Four closed vocabularies, no numbers."""

    op: OpName
    dir: Direction = "up"
    amount: Amount = "moderate"
    target: Target = ""

    @model_validator(mode="after")
    def _drop_unmaskable_region(self) -> "Op":
        # Normalised HERE and not in the compiler, so that the sentence, the
        # compiled grade and whatever the UI sends back all read the same field.
        # A verb the compiler cannot honour must not survive as far as
        # describe(), which would then report a move that never happened.
        if self.target in REGIONS and self.op in EFFECT_OPS:
            self.target = ""
        # The mirror of that rule for B6: a protect is a MASK, and the only
        # targets that are masks are the places and the things. A colour is not
        # one -- "spare the skin" would need the grade itself to be gated on
        # hue, which is a per-pixel bypass GradeSpec's 44 numbers cannot express
        # and a once-sampled matte of skin-coloured pixels would be strictly
        # worse than the hue qualifier `skin` already is on the verbs that take
        # it. Cleared rather than honoured, and describe() then says nothing
        # about it, because the failure to avoid is a sentence claiming the skin
        # was spared over a grade that went straight through it.
        if self.op in MASK_OPS and self.target not in REGIONS:
            self.target = ""
        # And the same rule for a COLOUR nobody will read. A verb outside
        # COLOUR_TARGETED has no per-hue mechanism at all, so a colour on one is
        # a word the compiler cannot honour -- cleared here rather than left to
        # reach describe(), for the reason the two rules above are: a sentence
        # that names a colour over a grade that moved the whole frame is worse
        # than one that never mentions it.
        if self.target and self.target not in REGIONS and self.op not in COLOUR_TARGETED:
            self.target = ""
        return self


class Intent(BaseModel):
    """Everything the model has to produce. Compare: GradeSpec is 44 floats."""

    ops: list[Op] = Field(default_factory=list)
    strength: Strength = "full"

    @staticmethod
    def llm_json_schema() -> dict:
        """Strict JSON schema for constrained decoding.

        Same rules spec.py's llm_json_schema() follows, for the same reason:
        Groq's strict mode requires `properties` AND `required` to list exactly
        the same keys, with additionalProperties False, at every object level. A
        property that is present but not required is rejected outright.

        No `description` strings and no minItems/maxItems. Descriptions belong in
        the system prompt (vibe.py's SYSTEM is the precedent) and array bounds
        are not enforced during constrained generation anyway — the same reason
        spec.RGB is an object rather than a 3-element array.
        """
        item_props = {
            "op": {"type": "string", "enum": list(OPS)},
            "dir": {"type": "string", "enum": list(DIRECTIONS)},
            "amount": {"type": "string", "enum": list(AMOUNTS)},
            "target": {"type": "string", "enum": list(TARGETS)},
        }
        item = {
            "type": "object",
            "properties": item_props,
            "required": list(item_props),
            "additionalProperties": False,
        }
        props = {
            "ops": {"type": "array", "items": item},
            "strength": {"type": "string", "enum": list(STRENGTHS)},
        }
        return {
            "type": "object",
            "properties": props,
            "required": list(props),
            "additionalProperties": False,
        }


# ---- rendering to English -------------------------------------------------

# (up phrase, down phrase) per verb. `{c}` is the target colour, for the two
# verbs whose target IS the colour rather than a selection.
_PHRASES: dict[str, tuple[str, str]] = {
    "exposure": ("brightened it", "darkened it"),
    "contrast": ("added contrast", "flattened the contrast"),
    "midtones": ("opened up the midtones", "darkened the midtones"),
    "shadows": ("lifted the shadows", "deepened the shadows"),
    "highlights": ("lifted the highlights", "pulled the highlights down"),
    # NOT "softened the highlights": `softness` already renders "softened it",
    # and two rows in the C3 list both saying "soft" -- one a blur, one a curve
    # -- is exactly the ambiguity that list exists to remove.
    "shoulder": ("rolled the highlights off", "let the highlights go hard"),
    "warmth": ("warmed it up", "cooled it down"),
    "tint": ("pushed it magenta", "pushed it green"),
    "saturation": ("richened the colour", "drained the colour"),
    "shadow_saturation": ("brought the colour back into the shadows",
                         "drained the colour out of the shadows"),
    "highlight_saturation": ("richened the highlights",
                            "drained the colour out of the highlights"),
    "shadow_tint": ("pushed {c} into the shadows", "pulled {c} out of the shadows"),
    "highlight_tint": ("pushed {c} into the highlights", "pulled {c} out of the highlights"),
    "grain": ("added grain", "took the grain out"),
    "glow": ("added a glow to the highlights", "took the glow off"),
    "vignette": ("darkened the corners", "brightened the corners"),
    "softness": ("softened it", "sharpened it"),
    "denoise": ("cleaned up the noise", "left the noise alone"),
    "fringe": ("added colour fringing", "took the fringing out"),
    # One phrase for both directions: there is no opposite of sparing something.
    # " it" is the slot _in_region fills, so this renders "left the sky alone".
    "protect": ("left it alone", "left it alone"),
}

# Verbs whose `target` selects WHICH PIXELS, rather than naming a colour to add.
# The three of them map one-to-one onto the three fields of a hue qualifier --
# saturation -> sat, exposure -> lum, warmth -> rot -- which is why hue-vs-hue
# cost this vocabulary NO new word: "warm up the greens" was already sayable and
# already had somewhere to land.
SELECTIVE = ("saturation", "exposure", "warmth")

# Every verb a COLOUR target means something on: SELECTIVE says which PIXELS
# move, the two tint verbs say which COLOUR is added. Named once because the
# validator below, describe() and INTENT_SYSTEM all have to agree about it --
# and until this existed only the prompt said it ("Every other verb ignores a
# colour target. Leave it '' on them"), with nothing enforcing it. Measured:
# 13 of the 18 verbs kept a colour target they never read, so `warmth` with
# target "green" produced the same GLOBAL temperature push as an untargeted
# one while describe() said only "warmed it up" -- a grade doing something
# other than what its own sentence claims, which is the failure this module
# exists to prevent.
COLOUR_TARGETED = SELECTIVE + ("shadow_tint", "highlight_tint")

# How each region reads in a sentence. "center" is `the middle` because nobody
# says "the center of the frame" out loud, and the sentence is the UI.
REGION_NAMES = {
    "top": "the top", "bottom": "the bottom",
    "left": "the left side", "right": "the right side",
    "center": "the middle", "edges": "the edges",
    # The semantic words already ARE how a person says them, so these are the
    # article and nothing else. "buildings" stays plural because that is what
    # the class covers -- a skyline, not one building.
    "sky": "the sky", "foliage": "the foliage", "person": "the person",
    "water": "the water", "buildings": "the buildings",
}

_ADVERB = {"subtle": " a little", "moderate": "", "strong": " a lot"}

# Default colour for a tint verb that arrived without one. Not an invention:
# teal shadows against warm highlights is the standing convention the vibe.py
# prompt already names, and a tint verb with no colour is otherwise a no-op.
DEFAULT_TINT = {"shadow_tint": "teal", "highlight_tint": "orange"}


def describe(intent: Intent) -> list[str]:
    """One short English phrase per operation, plus one for a reduced strength.

    Lower case, no trailing punctuation: these are list items in a UI, and
    compiler.compile_intent joins them into GradeSpec.rationale.
    """
    out = []
    for item in intent.ops:
        if item.op in MASK_OPS:
            # No direction and no adverb: a region is in or out, so "left the
            # sky alone a little" would describe a thing this cannot do. A
            # protect whose target was cleared by Op's validator protects
            # nothing and says nothing -- the alternative is a sentence
            # promising the model's unmaskable target was spared.
            if item.target:
                out.append(_in_region(_PHRASES[item.op][0], item.target))
            continue
        up, down = _PHRASES[item.op]
        phrase = up if item.dir == "up" else down
        # A region answers "which pixels"; a colour name answers either "which
        # pixels" (SELECTIVE) or "which colour to add" (the two tint verbs). So
        # the tint verbs still need a colour even when the target is a region --
        # the compiler falls back to DEFAULT_TINT there and this has to say the
        # same word, or the sentence names a colour the grade did not use.
        colour = DEFAULT_TINT.get(item.op, "") if item.target in REGIONS else \
            (item.target or DEFAULT_TINT.get(item.op, ""))
        phrase = phrase.format(c=colour) if "{c}" in phrase else phrase
        if item.target in REGIONS:
            phrase = _in_region(phrase, item.target)
        elif item.target and item.op in SELECTIVE:
            phrase += _in_the(item.target)
        out.append(phrase + _ADVERB[item.amount])
    if intent.strength != "full":
        out.append(f"applied the whole look at {STRENGTH_MIX[intent.strength]:.0%} strength")
    return out


def _in_the(target: str) -> str:
    return " in the skin tones" if target == "skin" else f" in the {target}s"


def _in_region(phrase: str, target: str) -> str:
    """A verb's phrase, aimed at a region. "darkened it" -> "darkened the top".

    Substitution rather than a second phrase table: the pronoun in "darkened
    it" / "warmed it up" is exactly the slot the region fills, so naming the
    region there gives the sentence a person would say. The verbs with no
    pronoun ("added contrast") take " in the middle" on the end instead, which
    is the only other shape English offers here.
    """
    name = REGION_NAMES[target]
    if " it" in phrase:
        return phrase.replace(" it", " " + name, 1)
    return f"{phrase} {'at' if target == 'edges' else 'in'} {name}"
